### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by datiti** [CodinGame/FallChallenge2020#5]
Hi,

There is a compilation error: _Game.java:[578,23] incompatible types: java.util.Optional<java.lang.Object> cannot be converted to java.util.Optional<com.codingame.game.spell.Spell>_

You will find below the details:

Java version: _java full version "15.0.1+9-18"_

Maven version:

_Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 15.0.1, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.2", arch: "x86_64", family: "mac"_

**Below the output while trying to compile the project:**

```
mvn compile
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.codingame.game:fall-2020:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.codingame.gameengine:module-endscreen:jar -> duplicate declaration of version ${gamengine.version} @ line 47, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building fall-2020 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fall-2020 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 38 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ fall-2020 ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 27 source files to /Volumes/HD2/X/github/CodinGame/FallChallenge2020/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Volumes/HD2/X/github/CodinGame/FallChallenge2020/src/main/java/com/codingame/game/Game.java:[577,35] cannot find symbol
  symbol:   method getId()
  location: variable spell of type java.lang.Object
[ERROR] /Volumes/HD2/X/github/CodinGame/FallChallenge2020/src/main/java/com/codingame/game/Game.java:[578,23] incompatible types: java.util.Optional<java.lang.Object> cannot be converted to java.util.Optional<com.codingame.game.spell.Spell>
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.399 s
[INFO] Finished at: 2021-01-20T14:23:57+01:00
[INFO] Final Memory: 17M/80M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project fall-2020: Compilation failure: Compilation failure:
[ERROR] /Volumes/HD2/X/github/CodinGame/FallChallenge2020/src/main/java/com/codingame/game/Game.java:[577,35] cannot find symbol
[ERROR]   symbol:   method getId()
[ERROR]   location: variable spell of type java.lang.Object
[ERROR] /Volumes/HD2/X/github/CodinGame/FallChallenge2020/src/main/java/com/codingame/game/Game.java:[578,23] incompatible types: java.util.Optional<java.lang.Object> cannot be converted to java.util.Optional<com.codingame.game.spell.Spell>
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Kind regards
Cyrille

**Comment by datiti** [comment]
Only occurs with JDK 15 despite the 1.8 configuration in pom.xml
It works with JDK 1.8
