### ISSUE TITLE
Unable to run locally - java: cannot find symbol

### ISSUE THREAD

**Issue by aadimator** [CodinGame/FallChallenge2020#2]
I'm pretty new to the CG Platform, but I'm excited to learn more about it and be active in the community. After reading a bunch of articles and forum posts, I'm still unable to set-up a local environment to work on the challenge.
I've cloned this repo, opened it up using IntelliJIdea, and tried running the Default agent, without any modification in the code whatsoever, but the code isn't compiling. It's giving the following error:
![image](https://user-images.githubusercontent.com/10383542/99340150-4ffc0f80-283c-11eb-9e16-4449070e08a5.png)

I'm using OracleJDK v14, and I'm on Windows 10. 

Could anyone please guide me what's the problem here and how might I be able to fix it? I want to be able to run and test my code locally so I can use language-specific IDEs and have source-control as well.

**Comment by omuric** [comment]
As you can see from [pom.xml](https://github.com/CodinGame/FallChallenge2020/blob/main/pom.xml#L13), this project is designed to be build with java 1.8 (JDK8).
java is not fully backwards compatible. This is why this project seems to fail to compile with JDK 14

If you are able to use the docker, you can try to build this project with the following command

```bash
docker run -it --rm -v "$(pwd)":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -w /usr/src/mymaven maven:3.6.3-ibmjava-8 mvn package
```

If you want to build in the IDE, you'll need to install the JDK 8 in your local environment

**Comment by omuric** [comment]
Here are the results of the build with JDK8 and JDK14

adoptopenjdk-8

```sh
docker run -it --rm -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.6.3-adoptopenjdk-8 mvn package

...

[INFO] Building jar: /usr/src/mymaven/target/fall-2020-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:16 min
[INFO] Finished at: 2020-11-17T04:22:16Z
[INFO] ------------------------------------------------------------------------

```

adoptopenjdk-14
```sh
docker run -it --rm -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3-adoptopenjdk-14 mvn package

... 

[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:13 min
[INFO] Finished at: 2020-11-17T04:23:51Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project fall-2020: Compilation failure: Compilation failure: 
[ERROR] /usr/src/mymaven/src/main/java/com/codingame/game/Game.java:[577,35] cannot find symbol
[ERROR]   symbol:   method getId()
[ERROR]   location: variable spell of type java.lang.Object
[ERROR] /usr/src/mymaven/src/main/java/com/codingame/game/Game.java:[578,23] incompatible types: java.util.Optional<java.lang.Object> cannot be converted to java.util.Optional<com.codingame.game.spell.Spell>
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

(If you don't delete the target directory after building with 8, it will still build successfully on 14 due to the cache...)

**Comment by aadimator** [comment]
Got it. Thanks for the quick reply. Much appreciated 🙂
